import type { AdaptiveLevel } from "./adaptive-difficulty";

// Drills focus on keigo (尊敬語 / 謙譲語 / 美化語 / 二重敬語), business email keigo,
// and handling real business/daily situations.
export type DrillType =
  | "sonkeigo"
  | "kenjougo"
  | "bikago"
  | "double-keigo"
  | "usage"
  | "keigo-conversion"
  | "cushion"
  | "email"
  | "service"
  | "situation";

export interface Drill {
  id: string;
  type: DrillType;
  level: AdaptiveLevel;
  promptJa: string;
  options: string[];
  correctIndex: number;
  questionEn: string;
  questionVi: string;
  explanationEn: string;
  explanationVi: string;
}

const Q = {
  son: {
    en: "Choose the correct 尊敬語 (respectful) expression.",
    vi: "Chọn cách nói 尊敬語 (tôn kính ngữ) đúng.",
  },
  ken: {
    en: "Choose the correct 謙譲語 (humble) expression.",
    vi: "Chọn cách nói 謙譲語 (khiêm nhường ngữ) đúng.",
  },
  sit: {
    en: "Which response best fits this real-life situation?",
    vi: "Câu nào phù hợp nhất với tình huống thực tế này?",
  },
  bika: {
    en: "Choose the correct 美化語 (beautified) form.",
    vi: "Chọn dạng 美化語 (mỹ hóa ngữ) đúng.",
  },
  dbl: {
    en: "Pick the correct keigo — avoid 二重敬語 (double honorifics).",
    vi: "Chọn kính ngữ đúng — tránh 二重敬語 (kính ngữ kép).",
  },
  mail: {
    en: "Choose the appropriate business-email expression.",
    vi: "Chọn cách viết email công việc phù hợp.",
  },
  usage: {
    en: "Respectful or humble? Choose based on who performs the action.",
    vi: "Tôn kính hay khiêm nhường? Chọn theo người thực hiện hành động.",
  },
  conv: {
    en: "Convert to correct keigo — choose the polished version.",
    vi: "Chuyển sang kính ngữ đúng — chọn cách nói lịch sự.",
  },
  cushion: {
    en: "Choose the correct cushion phrase (クッション言葉).",
    vi: "Chọn cụm đệm lịch sự (クッション言葉) đúng.",
  },
  service: {
    en: "Choose the correct service keigo — avoid バイト敬語 mistakes.",
    vi: "Chọn kính ngữ phục vụ đúng — tránh lỗi バイト敬語.",
  },
};

export const DRILLS: Drill[] = [
  // ===== 尊敬語 (respectful — raise the other person) =====
  {
    id: "son-irassharu",
    type: "sonkeigo",
    level: "N3",
    promptJa: "社長はもう___か。（尊敬語：来た）",
    options: ["来ましたか", "いらっしゃいましたか", "参りましたか", "伺いましたか"],
    correctIndex: 1,
    questionEn: Q.son.en,
    questionVi: Q.son.vi,
    explanationEn: "いらっしゃる is the respectful form of 来る/行く/いる. 参る and 伺う are humble (謙譲語) and cannot describe the president.",
    explanationVi: "いらっしゃる là tôn kính ngữ của 来る/行く/いる. 参る, 伺う là khiêm nhường ngữ, không dùng cho giám đốc.",
  },
  {
    id: "son-meshiagaru",
    type: "sonkeigo",
    level: "N3",
    promptJa: "どうぞ、こちらのお菓子を___ください。（尊敬語：食べる）",
    options: ["召し上がって", "いただいて", "食べて", "頂戴して"],
    correctIndex: 0,
    questionEn: Q.son.en,
    questionVi: Q.son.vi,
    explanationEn: "召し上がる is the respectful form of 食べる/飲む. いただく and 頂戴する are humble.",
    explanationVi: "召し上がる là tôn kính ngữ của 食べる/飲む. いただく, 頂戴する là khiêm nhường ngữ.",
  },
  {
    id: "son-goran",
    type: "sonkeigo",
    level: "N3",
    promptJa: "資料はもう___ましたか。（尊敬語：見る）",
    options: ["拝見し", "ご覧になり", "お見せし", "拝読し"],
    correctIndex: 1,
    questionEn: Q.son.en,
    questionVi: Q.son.vi,
    explanationEn: "ご覧になる is the respectful form of 見る. 拝見する/拝読する are humble.",
    explanationVi: "ご覧になる là tôn kính ngữ của 見る. 拝見する, 拝読する là khiêm nhường ngữ.",
  },
  {
    id: "son-ossharu",
    type: "sonkeigo",
    level: "N3",
    promptJa: "お名前は何と___ますか。（尊敬語：言う）",
    options: ["申し", "おっしゃい", "言い", "申し上げ"],
    correctIndex: 1,
    questionEn: Q.son.en,
    questionVi: Q.son.vi,
    explanationEn: "おっしゃる is the respectful form of 言う. 申す/申し上げる are humble.",
    explanationVi: "おっしゃる là tôn kính ngữ của 言う. 申す, 申し上げる là khiêm nhường ngữ.",
  },
  {
    id: "son-nasaru",
    type: "sonkeigo",
    level: "N2",
    promptJa: "部長は何時に出発___ますか。（尊敬語：する）",
    options: ["いたし", "なさい", "し", "させ"],
    correctIndex: 1,
    questionEn: Q.son.en,
    questionVi: Q.son.vi,
    explanationEn: "なさる is the respectful form of する (→なさいます). いたす is humble.",
    explanationVi: "なさる là tôn kính ngữ của する (→なさいます). いたす là khiêm nhường ngữ.",
  },
  {
    id: "son-oninaru",
    type: "sonkeigo",
    level: "N3",
    promptJa: "先生はもうお帰りに___。（尊敬語のパターン）",
    options: ["なりました", "いたしました", "しました", "させました"],
    correctIndex: 0,
    questionEn: Q.son.en,
    questionVi: Q.son.vi,
    explanationEn: "「お＋ますstem＋になる」is the general respectful pattern: お帰りになる = (someone respected) goes home.",
    explanationVi: "Mẫu 「お＋thân ます＋になる」 là mẫu tôn kính chung: お帰りになる = (người được kính) về nhà.",
  },
  {
    id: "son-kudasaru",
    type: "sonkeigo",
    level: "N3",
    promptJa: "先生が推薦状を書いて___。（尊敬語：くれた）",
    options: ["くださいました", "いただきました", "さしあげました", "もらいました"],
    correctIndex: 0,
    questionEn: Q.son.en,
    questionVi: Q.son.vi,
    explanationEn: "くださる is the respectful form of くれる — the respected giver acts for you. いただく is humble (you receive).",
    explanationVi: "くださる là tôn kính ngữ của くれる — người được kính làm cho mình. いただく là khiêm nhường (mình nhận).",
  },

  // ===== 謙譲語 (humble — lower yourself) =====
  {
    id: "ken-mairu",
    type: "kenjougo",
    level: "N3",
    promptJa: "明日、10時に御社へ___。（謙譲語：行く）",
    options: ["いらっしゃいます", "参ります", "おいでになります", "行かれます"],
    correctIndex: 1,
    questionEn: Q.ken.en,
    questionVi: Q.ken.vi,
    explanationEn: "参る (or 伺う) is the humble form of 行く/来る. The other three are respectful and can't describe your own action.",
    explanationVi: "参る (hoặc 伺う) là khiêm nhường ngữ của 行く/来る. Ba đáp án kia là tôn kính, không dùng cho hành động của mình.",
  },
  {
    id: "ken-haiken",
    type: "kenjougo",
    level: "N3",
    promptJa: "頂いた資料を___ました。（謙譲語：見る）",
    options: ["ご覧になり", "拝見し", "見え", "お見せになり"],
    correctIndex: 1,
    questionEn: Q.ken.en,
    questionVi: Q.ken.vi,
    explanationEn: "拝見する is the humble form of 見る. ご覧になる is respectful.",
    explanationVi: "拝見する là khiêm nhường ngữ của 見る. ご覧になる là tôn kính ngữ.",
  },
  {
    id: "ken-mosu",
    type: "kenjougo",
    level: "N3",
    promptJa: "はじめまして、田中と___。（謙譲語：言う）",
    options: ["おっしゃいます", "申します", "言われます", "ございます"],
    correctIndex: 1,
    questionEn: Q.ken.en,
    questionVi: Q.ken.vi,
    explanationEn: "申す/申し上げる is the humble form of 言う, used to give your own name. おっしゃる is respectful.",
    explanationVi: "申す/申し上げる là khiêm nhường ngữ của 言う, dùng khi xưng tên mình. おっしゃる là tôn kính ngữ.",
  },
  {
    id: "ken-itasu",
    type: "kenjougo",
    level: "N3",
    promptJa: "私がご案内___。（謙譲語：する）",
    options: ["なさいます", "いたします", "されます", "あそばします"],
    correctIndex: 1,
    questionEn: Q.ken.en,
    questionVi: Q.ken.vi,
    explanationEn: "いたす is the humble form of する. なさる is respectful.",
    explanationVi: "いたす là khiêm nhường ngữ của する. なさる là tôn kính ngữ.",
  },
  {
    id: "ken-ukagau",
    type: "kenjougo",
    level: "N2",
    promptJa: "一点、___たいことがございます。（謙譲語：聞く・尋ねる）",
    options: ["お聞きになり", "伺い", "お尋ねになり", "聞かれ"],
    correctIndex: 1,
    questionEn: Q.ken.en,
    questionVi: Q.ken.vi,
    explanationEn: "伺う is the humble form of 聞く/尋ねる/訪ねる. The お～になる options are respectful.",
    explanationVi: "伺う là khiêm nhường ngữ của 聞く/尋ねる/訪ねる. Các dạng お～になる là tôn kính.",
  },
  {
    id: "ken-itadaku",
    type: "kenjougo",
    level: "N3",
    promptJa: "部長にお土産を___ました。（謙譲語：もらう）",
    options: ["くださり", "いただき", "さしあげ", "くれ"],
    correctIndex: 1,
    questionEn: Q.ken.en,
    questionVi: Q.ken.vi,
    explanationEn: "いただく is the humble form of もらう (you receive). くださる is respectful; さしあげる means to give.",
    explanationVi: "いただく là khiêm nhường ngữ của もらう (mình nhận). くださる là tôn kính; さしあげる nghĩa là biếu/tặng.",
  },
  {
    id: "ken-omenikakaru",
    type: "kenjougo",
    level: "N1",
    promptJa: "先日、社長に___。（謙譲語：会った）",
    options: ["お会いになりました", "お目にかかりました", "お見えになりました", "会われました"],
    correctIndex: 1,
    questionEn: Q.ken.en,
    questionVi: Q.ken.vi,
    explanationEn: "お目にかかる is the humble form of 会う. お会いになる/お見えになる/会われる are respectful.",
    explanationVi: "お目にかかる là khiêm nhường ngữ của 会う. お会いになる/お見えになる/会われる là tôn kính.",
  },
  {
    id: "ken-zonjiru",
    type: "kenjougo",
    level: "N2",
    promptJa: "その件については___。（謙譲語：知っている）",
    options: ["ご存じです", "存じております", "お知りです", "知られています"],
    correctIndex: 1,
    questionEn: Q.ken.en,
    questionVi: Q.ken.vi,
    explanationEn: "存じております/存じ上げる is the humble form of 知っている. ご存じ is respectful.",
    explanationVi: "存じております/存じ上げる là khiêm nhường ngữ của 知っている. ご存じ là tôn kính.",
  },

  // ===== 実践 (handling real business/daily situations) =====
  {
    id: "sit-office-phone",
    type: "situation",
    level: "N3",
    promptJa: "会社の電話を取ったときの第一声として最も適切なのは？",
    options: ["もしもし。", "はい、〇〇会社でございます。", "誰ですか。", "はい、なんでしょう。"],
    correctIndex: 1,
    questionEn: Q.sit.en,
    questionVi: Q.sit.vi,
    explanationEn: "At work you answer with the company name + でございます, not もしもし (that's for private calls).",
    explanationVi: "Ở công ty, khi bắt máy nói tên công ty + でございます, không dùng もしもし (chỉ dùng cho cuộc gọi riêng).",
  },
  {
    id: "sit-leave-message",
    type: "situation",
    level: "N3",
    promptJa: "電話で相手が不在。伝言を頼むときの丁寧な言い方は？",
    options: ["伝えておいて。", "ご伝言をお願いできますでしょうか。", "言っといて。", "伝えてね。"],
    correctIndex: 1,
    questionEn: Q.sit.en,
    questionVi: Q.sit.vi,
    explanationEn: "ご伝言をお願いできますでしょうか is the polite way to ask someone to relay a message.",
    explanationVi: "ご伝言をお願いできますでしょうか là cách lịch sự để nhờ chuyển lời nhắn.",
  },
  {
    id: "sit-decline-invite",
    type: "situation",
    level: "N3",
    promptJa: "上司の飲みの誘いを、失礼なく断るなら？",
    options: ["行きません。", "せっかくですが、あいにく先約がございまして…。", "無理です。", "興味ないです。"],
    correctIndex: 1,
    questionEn: Q.sit.en,
    questionVi: Q.sit.vi,
    explanationEn: "「せっかくですが」+ a soft reason (先約がございまして…) declines politely without offending.",
    explanationVi: "「せっかくですが」+ lý do nhẹ (先約がございまして…) để từ chối lịch sự mà không mất lòng.",
  },
  {
    id: "sit-apology-client",
    type: "situation",
    level: "N2",
    promptJa: "納品ミスを取引先に謝罪するとき、最も適切なのは？",
    options: ["ごめんなさい。", "この度はご迷惑をおかけし、誠に申し訳ございません。", "すいませんでした。", "こちらのミスです。"],
    correctIndex: 1,
    questionEn: Q.sit.en,
    questionVi: Q.sit.vi,
    explanationEn: "To a client, use the full formal apology: ご迷惑をおかけし、誠に申し訳ございません.",
    explanationVi: "Với đối tác, dùng lời xin lỗi trang trọng đầy đủ: ご迷惑をおかけし、誠に申し訳ございません.",
  },
  {
    id: "sit-visit-greeting",
    type: "situation",
    level: "N3",
    promptJa: "取引先を訪問して交わす最初の挨拶は？",
    options: ["どうも。", "いつもお世話になっております。", "こんにちは、お元気ですか。", "やあ、どうも。"],
    correctIndex: 1,
    questionEn: Q.sit.en,
    questionVi: Q.sit.vi,
    explanationEn: "いつもお世話になっております is the standard business greeting to a client or partner.",
    explanationVi: "いつもお世話になっております là câu chào chuẩn trong kinh doanh với khách hàng/đối tác.",
  },
  {
    id: "sit-ask-wait",
    type: "situation",
    level: "N4",
    promptJa: "お客様に少しの間、待ってもらいたいとき？",
    options: ["ちょっと待って。", "少々お待ちいただけますか。", "待っててね。", "待ってて、すぐだから。"],
    correctIndex: 1,
    questionEn: Q.sit.en,
    questionVi: Q.sit.vi,
    explanationEn: "少々お待ちいただけますか politely asks a customer to wait a moment.",
    explanationVi: "少々お待ちいただけますか là cách lịch sự nhờ khách chờ một chút.",
  },
  {
    id: "sit-meishi",
    type: "situation",
    level: "N2",
    promptJa: "名刺交換で、相手の名刺を受け取るときの言葉は？",
    options: ["どうも。", "頂戴いたします。", "もらいますね。", "ありがとう。"],
    correctIndex: 1,
    questionEn: Q.sit.en,
    questionVi: Q.sit.vi,
    explanationEn: "頂戴いたします is the set phrase when receiving someone's business card.",
    explanationVi: "頂戴いたします là câu cố định khi nhận danh thiếp của đối phương.",
  },
  {
    id: "sit-report-open",
    type: "situation",
    level: "N3",
    promptJa: "忙しそうな上司に報告を切り出すときの一言は？",
    options: ["ねえ、聞いてください。", "お忙しいところ失礼いたします。ご報告があります。", "あの、ちょっと。", "今、報告いいですか。"],
    correctIndex: 1,
    questionEn: Q.sit.en,
    questionVi: Q.sit.vi,
    explanationEn: "お忙しいところ失礼いたします acknowledges the boss is busy before you report — polished business manners.",
    explanationVi: "お忙しいところ失礼いたします thể hiện bạn hiểu sếp đang bận trước khi báo cáo — tác phong chuẩn.",
  },
  {
    id: "sit-leave-office",
    type: "situation",
    level: "N4",
    promptJa: "同僚より先に退社するときの挨拶は？",
    options: ["じゃあね。", "お先に失礼します。", "帰ります。", "さようなら。"],
    correctIndex: 1,
    questionEn: Q.sit.en,
    questionVi: Q.sit.vi,
    explanationEn: "お先に失礼します is the standard phrase for leaving the office before your colleagues.",
    explanationVi: "お先に失礼します là câu chuẩn khi ra về trước đồng nghiệp.",
  },
  {
    id: "sit-polite-complaint",
    type: "situation",
    level: "N3",
    promptJa: "レストランで料理に髪の毛が。丁寧に伝えるなら？",
    options: ["これ、髪の毛入ってるよ。", "すみません、こちらに髪の毛が入っているようなのですが。", "髪の毛！ありえない。", "ちょっと、これ何。"],
    correctIndex: 1,
    questionEn: Q.sit.en,
    questionVi: Q.sit.vi,
    explanationEn: "Softening with 〜ようなのですが lets you raise a complaint politely instead of accusingly.",
    explanationVi: "Dùng 〜ようなのですが để nêu khiếu nại một cách nhẹ nhàng, lịch sự thay vì gay gắt.",
  },

  // ===== 美化語 (beautified language — お / ご prefixes) =====
  {
    id: "bika-hanashi",
    type: "bikago",
    level: "N4",
    promptJa: "和語の「話」を上品に言うと？（美化語）",
    options: ["ご話", "お話", "御話し", "話ご"],
    correctIndex: 1,
    questionEn: Q.bika.en,
    questionVi: Q.bika.vi,
    explanationEn: "Native Japanese (和語) words take お: お話, お名前, お金. Sino-Japanese words usually take ご.",
    explanationVi: "Từ thuần Nhật (和語) dùng お: お話, お名前, お金. Từ Hán-Nhật thường dùng ご.",
  },
  {
    id: "bika-renraku",
    type: "bikago",
    level: "N4",
    promptJa: "漢語の「連絡」に美化の接頭語をつけると？",
    options: ["お連絡", "ご連絡", "御連絡お", "連絡ご"],
    correctIndex: 1,
    questionEn: Q.bika.en,
    questionVi: Q.bika.vi,
    explanationEn: "Sino-Japanese (漢語) words usually take ご: ご連絡, ご住所, ご相談.",
    explanationVi: "Từ Hán-Nhật (漢語) thường dùng ご: ご連絡, ご住所, ご相談.",
  },
  {
    id: "bika-denwa",
    type: "bikago",
    level: "N3",
    promptJa: "「電話」は漢語だが、慣用的にどちらをつける？",
    options: ["お電話", "ご電話", "御電話ご", "電話お"],
    correctIndex: 0,
    questionEn: Q.bika.en,
    questionVi: Q.bika.vi,
    explanationEn: "電話 is an exception: it takes お (お電話), like お料理, お茶, お米, even though it's a 漢語.",
    explanationVi: "電話 là ngoại lệ: dùng お (お電話), giống お料理, お茶, お米, dù là từ Hán-Nhật.",
  },
  {
    id: "bika-vs-sonkeigo",
    type: "bikago",
    level: "N2",
    promptJa: "次のうち、相手を高める敬語ではなく『美化語』はどれ？",
    options: ["ご覧になる", "お料理", "いらっしゃる", "おっしゃる"],
    correctIndex: 1,
    questionEn: Q.bika.en,
    questionVi: Q.bika.vi,
    explanationEn: "お料理/お茶 simply make your speech refined (美化語). The others elevate the listener (尊敬語).",
    explanationVi: "お料理/お茶 chỉ làm lời nói trang nhã (美化語). Các từ kia nâng cao người nghe (尊敬語).",
  },
  {
    id: "bika-gohan",
    type: "bikago",
    level: "N4",
    promptJa: "日常で「飯」を上品に言うと？（美化語）",
    options: ["お飯", "ご飯", "御飯お", "飯ご"],
    correctIndex: 1,
    questionEn: Q.bika.en,
    questionVi: Q.bika.vi,
    explanationEn: "ご飯 (ごはん) is the everyday beautified word for a meal/cooked rice.",
    explanationVi: "ご飯 (ごはん) là từ mỹ hóa thông dụng cho bữa cơm/cơm.",
  },

  // ===== 二重敬語 (double honorifics — choose the correct single form) =====
  {
    id: "dbl-ossharu",
    type: "double-keigo",
    level: "N2",
    promptJa: "正しい敬語はどれ？（社長が「言った」）",
    options: ["社長がおっしゃられました", "社長がおっしゃいました", "社長が申されました", "社長が言わされました"],
    correctIndex: 1,
    questionEn: Q.dbl.en,
    questionVi: Q.dbl.vi,
    explanationEn: "おっしゃる is already respectful; adding られる (おっしゃられる) is 二重敬語. Use おっしゃいました.",
    explanationVi: "おっしゃる vốn đã là tôn kính; thêm られる (おっしゃられる) là 二重敬語. Dùng おっしゃいました.",
  },
  {
    id: "dbl-goran",
    type: "double-keigo",
    level: "N2",
    promptJa: "「見る」の尊敬語で正しいのは？",
    options: ["ご覧になられる", "ご覧になる", "拝見なさる", "お見になる"],
    correctIndex: 1,
    questionEn: Q.dbl.en,
    questionVi: Q.dbl.vi,
    explanationEn: "ご覧になる is correct. ご覧になられる doubles the honorific (ご覧になる + られる).",
    explanationVi: "ご覧になる là đúng. ご覧になられる bị kép kính ngữ (ご覧になる + られる).",
  },
  {
    id: "dbl-meshiagaru",
    type: "double-keigo",
    level: "N1",
    promptJa: "「食べる」の尊敬語で正しいのは？",
    options: ["お召し上がりになる", "召し上がる", "召し上がられる", "お食べになられる"],
    correctIndex: 1,
    questionEn: Q.dbl.en,
    questionVi: Q.dbl.vi,
    explanationEn: "召し上がる is already respectful. お召し上がりになる and 召し上がられる are 二重敬語.",
    explanationVi: "召し上がる vốn đã tôn kính. お召し上がりになる và 召し上がられる là 二重敬語.",
  },
  {
    id: "dbl-irassharu",
    type: "double-keigo",
    level: "N1",
    promptJa: "「来る」の尊敬語で自然なのは？",
    options: ["おいでになられる", "いらっしゃる", "お越しになられる", "参られる"],
    correctIndex: 1,
    questionEn: Q.dbl.en,
    questionVi: Q.dbl.vi,
    explanationEn: "いらっしゃる/お越しになる are correct singles; adding られる makes 二重敬語. 参る is humble, so 参られる is wrong.",
    explanationVi: "いらっしゃる/お越しになる là dạng đơn đúng; thêm られる thành 二重敬語. 参る là khiêm nhường nên 参られる sai.",
  },
  {
    id: "dbl-oyomi",
    type: "double-keigo",
    level: "N2",
    promptJa: "「読む」の尊敬語で正しいのは？",
    options: ["お読みになられる", "お読みになる", "拝読される", "お読まれになる"],
    correctIndex: 1,
    questionEn: Q.dbl.en,
    questionVi: Q.dbl.vi,
    explanationEn: "お読みになる is correct. お読みになられる is 二重敬語; 拝読する is humble, not respectful.",
    explanationVi: "お読みになる là đúng. お読みになられる là 二重敬語; 拝読する là khiêm nhường, không phải tôn kính.",
  },

  // ===== メール敬語 (business-email set phrases) =====
  {
    id: "mail-open-external",
    type: "email",
    level: "N3",
    promptJa: "社外へのメールの書き出しとして適切なのは？",
    options: ["お疲れさまです。", "いつもお世話になっております。", "こんにちは。", "どうも。"],
    correctIndex: 1,
    questionEn: Q.mail.en,
    questionVi: Q.mail.vi,
    explanationEn: "いつもお世話になっております is the standard opening for external business email. お疲れさまです is for internal.",
    explanationVi: "いつもお世話になっております là câu mở đầu chuẩn cho email gửi ngoài công ty. お疲れさまです dùng nội bộ.",
  },
  {
    id: "mail-open-internal",
    type: "email",
    level: "N3",
    promptJa: "社内メールの書き出しとして自然なのは？",
    options: ["お世話になっております。", "お疲れさまです。", "拝啓、時下ますます。", "ご苦労さまです。"],
    correctIndex: 1,
    questionEn: Q.mail.en,
    questionVi: Q.mail.vi,
    explanationEn: "Internal emails open with お疲れさまです. ご苦労さま sounds condescending toward superiors.",
    explanationVi: "Email nội bộ mở đầu bằng お疲れさまです. ご苦労さま nghe bề trên khi nói với cấp trên.",
  },
  {
    id: "mail-attach",
    type: "email",
    level: "N3",
    promptJa: "資料を添付したことを伝える表現は？",
    options: ["ファイルつけときました。", "資料を添付いたしましたので、ご確認ください。", "資料送るね。", "資料あります。"],
    correctIndex: 1,
    questionEn: Q.mail.en,
    questionVi: Q.mail.vi,
    explanationEn: "資料を添付いたしましたので、ご確認ください is the standard way to note an attachment.",
    explanationVi: "資料を添付いたしましたので、ご確認ください là cách chuẩn để báo có tệp đính kèm.",
  },
  {
    id: "mail-request-reply",
    type: "email",
    level: "N2",
    promptJa: "返信を丁寧に依頼する表現は？",
    options: ["早く返事して。", "お忙しいところ恐縮ですが、ご返信いただけますと幸いです。", "返信ちょうだい。", "返事待ってます。"],
    correctIndex: 1,
    questionEn: Q.mail.en,
    questionVi: Q.mail.vi,
    explanationEn: "「〜いただけますと幸いです」politely requests a reply while acknowledging the other's busyness.",
    explanationVi: "「〜いただけますと幸いです」nhờ phản hồi một cách lịch sự, có để ý đến việc đối phương bận.",
  },
  {
    id: "mail-late-reply",
    type: "email",
    level: "N2",
    promptJa: "返信が遅れたときのお詫びとして適切なのは？",
    options: ["遅れてごめん。", "ご返信が遅くなり、申し訳ございません。", "返事おそくなった。", "すまん、忙しくて。"],
    correctIndex: 1,
    questionEn: Q.mail.en,
    questionVi: Q.mail.vi,
    explanationEn: "ご返信が遅くなり、申し訳ございません is the proper apology for a late reply.",
    explanationVi: "ご返信が遅くなり、申し訳ございません là lời xin lỗi đúng mực khi phản hồi trễ.",
  },
  {
    id: "mail-closing",
    type: "email",
    level: "N3",
    promptJa: "メールの結びの言葉として適切なのは？",
    options: ["じゃあ、よろしく。", "何卒よろしくお願い申し上げます。", "そういうことで。", "以上、おわり。"],
    correctIndex: 1,
    questionEn: Q.mail.en,
    questionVi: Q.mail.vi,
    explanationEn: "何卒よろしくお願い申し上げます is the standard formal closing line for business email.",
    explanationVi: "何卒よろしくお願い申し上げます là câu kết trang trọng chuẩn cho email công việc.",
  },

  // ===== 使い分け (respectful vs humble — decide by who acts) =====
  {
    id: "use-watashi-miru",
    type: "usage",
    level: "N3",
    promptJa: "「私がこの資料を___。」（見る）",
    options: ["ご覧になります", "拝見します", "見られます", "お見えになります"],
    correctIndex: 1,
    questionEn: Q.usage.en,
    questionVi: Q.usage.vi,
    explanationEn: "The subject is 私 (myself), so use 謙譲語: 拝見する. Respectful forms are only for others.",
    explanationVi: "Chủ ngữ là 私 (bản thân), nên dùng 謙譲語: 拝見する. Dạng tôn kính chỉ dùng cho người khác.",
  },
  {
    id: "use-okyaku-kuru",
    type: "usage",
    level: "N3",
    promptJa: "「お客様が3時に___。」（来る）",
    options: ["参ります", "いらっしゃいます", "伺います", "申します"],
    correctIndex: 1,
    questionEn: Q.usage.en,
    questionVi: Q.usage.vi,
    explanationEn: "The subject is お客様 (the other person), so use 尊敬語: いらっしゃる. 参る/伺う are humble.",
    explanationVi: "Chủ ngữ là お客様 (người khác), nên dùng 尊敬語: いらっしゃる. 参る/伺う là khiêm nhường.",
  },
  {
    id: "use-watashi-iku",
    type: "usage",
    level: "N2",
    promptJa: "「私が明日、御社に___。」（行く）",
    options: ["いらっしゃいます", "伺います", "おいでになります", "来られます"],
    correctIndex: 1,
    questionEn: Q.usage.en,
    questionVi: Q.usage.vi,
    explanationEn: "You go to the client, so lower yourself with 謙譲語: 伺う/参る. The rest are respectful.",
    explanationVi: "Mình đến chỗ khách, nên hạ mình bằng 謙譲語: 伺う/参る. Các dạng kia là tôn kính.",
  },
  {
    id: "use-sensei-miru",
    type: "usage",
    level: "N3",
    promptJa: "「先生が私の作文を___。」（見る）",
    options: ["拝見しました", "ご覧になりました", "見えました", "拝読しました"],
    correctIndex: 1,
    questionEn: Q.usage.en,
    questionVi: Q.usage.vi,
    explanationEn: "The subject is 先生, so use 尊敬語: ご覧になる. 拝見/拝読 would wrongly humble the teacher.",
    explanationVi: "Chủ ngữ là 先生, nên dùng 尊敬語: ご覧になる. 拝見/拝読 sẽ hạ thấp thầy — sai.",
  },
  {
    id: "use-watashi-kiku",
    type: "usage",
    level: "N2",
    promptJa: "「（私が）お客様のお名前を___。」（聞く・尋ねる）",
    options: ["お聞きになります", "伺います", "お尋ねになります", "聞かれます"],
    correctIndex: 1,
    questionEn: Q.usage.en,
    questionVi: Q.usage.vi,
    explanationEn: "You ask, so use 謙譲語: 伺う. お聞きになる/お尋ねになる elevate the other person, not you.",
    explanationVi: "Mình hỏi, nên dùng 謙譲語: 伺う. お聞きになる/お尋ねになる nâng người khác chứ không phải mình.",
  },
  {
    id: "use-shacho-iu",
    type: "usage",
    level: "N3",
    promptJa: "「社長が会議で___。」（言う）",
    options: ["申しました", "おっしゃいました", "申し上げました", "言わせました"],
    correctIndex: 1,
    questionEn: Q.usage.en,
    questionVi: Q.usage.vi,
    explanationEn: "The subject is 社長, so use 尊敬語: おっしゃる. 申す/申し上げる are humble (for yourself).",
    explanationVi: "Chủ ngữ là 社長, nên dùng 尊敬語: おっしゃる. 申す/申し上げる là khiêm nhường (cho bản thân).",
  },

  // ===== 敬語変換 (convert plain speech → keigo) =====
  {
    id: "conv-wait",
    type: "keigo-conversion",
    level: "N3",
    promptJa: "「ちょっと待って」を丁寧に言うと？",
    options: ["ちょっと待ってね。", "少々お待ちください。", "待ってて。", "待ちなさい。"],
    correctIndex: 1,
    questionEn: Q.conv.en,
    questionVi: Q.conv.vi,
    explanationEn: "少々お待ちください is the polite equivalent of 'please wait a moment'.",
    explanationVi: "少々お待ちください là cách lịch sự của 'chờ một chút'.",
  },
  {
    id: "conv-ok",
    type: "keigo-conversion",
    level: "N3",
    promptJa: "「これでいい？」を丁寧に確認すると？",
    options: ["これでいい？", "これでよろしいでしょうか。", "これで大丈夫？", "これでOK？"],
    correctIndex: 1,
    questionEn: Q.conv.en,
    questionVi: Q.conv.vi,
    explanationEn: "よろしいでしょうか is the polite way to confirm 'is this okay?'.",
    explanationVi: "よろしいでしょうか là cách lịch sự để xác nhận 'thế này được chưa?'.",
  },
  {
    id: "conv-know",
    type: "keigo-conversion",
    level: "N3",
    promptJa: "相手に「知ってる？」を尊敬語で聞くと？",
    options: ["知ってる？", "ご存じですか。", "知ってますか。", "存じてますか。"],
    correctIndex: 1,
    questionEn: Q.conv.en,
    questionVi: Q.conv.vi,
    explanationEn: "ご存じですか is respectful. 存じる is humble, so 存じてますか wrongly humbles the listener.",
    explanationVi: "ご存じですか là tôn kính. 存じる là khiêm nhường, nên 存じてますか hạ thấp người nghe — sai.",
  },
  {
    id: "conv-receive",
    type: "keigo-conversion",
    level: "N2",
    promptJa: "「これ、もらえる？」を丁寧な依頼にすると？",
    options: ["これ、もらえる？", "こちら、いただけますでしょうか。", "これちょうだい。", "これくれる？"],
    correctIndex: 1,
    questionEn: Q.conv.en,
    questionVi: Q.conv.vi,
    explanationEn: "いただけますでしょうか politely and humbly asks to receive something.",
    explanationVi: "いただけますでしょうか là cách nhờ nhận đồ một cách lịch sự, khiêm nhường.",
  },
  {
    id: "conv-show",
    type: "keigo-conversion",
    level: "N2",
    promptJa: "「見せて」を尊敬・丁寧にお願いすると？",
    options: ["見せて。", "お見せいただけますか。", "見せてくれる？", "見せろ。"],
    correctIndex: 1,
    questionEn: Q.conv.en,
    questionVi: Q.conv.vi,
    explanationEn: "Use お見せいただけますか to politely ask the other person to show you something.",
    explanationVi: "Dùng お見せいただけますか để lịch sự nhờ đối phương cho xem.",
  },
  {
    id: "conv-help",
    type: "keigo-conversion",
    level: "N2",
    promptJa: "「悪いけど手伝って」をビジネスの言い方にすると？",
    options: ["悪いけど手伝って。", "恐れ入りますが、お手伝いいただけますか。", "ちょっと手伝ってよ。", "手伝って。"],
    correctIndex: 1,
    questionEn: Q.conv.en,
    questionVi: Q.conv.vi,
    explanationEn: "Add a cushion (恐れ入りますが) + humble request (お手伝いいただけますか) for business.",
    explanationVi: "Thêm cụm đệm (恐れ入りますが) + lời nhờ khiêm nhường (お手伝いいただけますか) cho công việc.",
  },

  // ===== クッション言葉 (softening phrases) =====
  {
    id: "cushion-request",
    type: "cushion",
    level: "N3",
    promptJa: "依頼の前に添える言葉として適切なのは？（「___、確認をお願いできますか。」）",
    options: ["とにかく", "恐れ入りますが", "まあ", "ていうか"],
    correctIndex: 1,
    questionEn: Q.cushion.en,
    questionVi: Q.cushion.vi,
    explanationEn: "恐れ入りますが softens a request before you ask something of someone.",
    explanationVi: "恐れ入りますが làm dịu lời nhờ trước khi yêu cầu ai đó.",
  },
  {
    id: "cushion-decline",
    type: "cushion",
    level: "N3",
    promptJa: "誘いを断るときの前置きとして適切なのは？",
    options: ["悪いけど", "せっかくですが", "とりあえず", "別に"],
    correctIndex: 1,
    questionEn: Q.cushion.en,
    questionVi: Q.cushion.vi,
    explanationEn: "せっかくですが acknowledges the offer before you politely decline.",
    explanationVi: "せっかくですが ghi nhận lời mời trước khi từ chối lịch sự.",
  },
  {
    id: "cushion-ask",
    type: "cushion",
    level: "N2",
    promptJa: "尋ねにくいことを聞く前置きとして適切なのは？",
    options: ["ぶっちゃけ", "差し支えなければ", "一応", "なんか"],
    correctIndex: 1,
    questionEn: Q.cushion.en,
    questionVi: Q.cushion.vi,
    explanationEn: "差し支えなければ ('if it's not a problem') softens a sensitive question.",
    explanationVi: "差し支えなければ ('nếu không phiền') làm dịu câu hỏi tế nhị.",
  },
  {
    id: "cushion-trouble",
    type: "cushion",
    level: "N3",
    promptJa: "相手に手間をかける依頼の前に添えるのは？",
    options: ["悪いね", "お手数ですが", "とりあえず", "ちょっと"],
    correctIndex: 1,
    questionEn: Q.cushion.en,
    questionVi: Q.cushion.vi,
    explanationEn: "お手数ですが ('sorry to trouble you') precedes a request that requires effort.",
    explanationVi: "お手数ですが ('phiền bạn') dùng trước lời nhờ khiến đối phương mất công.",
  },
  {
    id: "cushion-object",
    type: "cushion",
    level: "N2",
    promptJa: "反論や訂正を切り出す前置きとして適切なのは？",
    options: ["いや", "申し上げにくいのですが", "ていうか", "でもさ"],
    correctIndex: 1,
    questionEn: Q.cushion.en,
    questionVi: Q.cushion.vi,
    explanationEn: "申し上げにくいのですが softens disagreement or a correction before you state it.",
    explanationVi: "申し上げにくいのですが làm dịu sự phản đối/đính chính trước khi nói ra.",
  },
  {
    id: "cushion-refuse-offer",
    type: "cushion",
    level: "N2",
    promptJa: "相手の申し出を断るときの前置きは？",
    options: ["いらない", "あいにくですが", "べつに", "むりむり"],
    correctIndex: 1,
    questionEn: Q.cushion.en,
    questionVi: Q.cushion.vi,
    explanationEn: "あいにくですが ('unfortunately') politely prefaces turning down an offer.",
    explanationVi: "あいにくですが ('rất tiếc') dùng để mở đầu lịch sự khi từ chối lời đề nghị.",
  },

  // ===== 接客敬語 (service keigo — avoid バイト敬語 errors) =====
  {
    id: "svc-azukari",
    type: "service",
    level: "N3",
    promptJa: "会計で1000円を受け取るとき、正しいのは？",
    options: ["1000円からお預かりします。", "1000円をお預かりします。", "1000円からいただきます。", "1000円のほうお預かりします。"],
    correctIndex: 1,
    questionEn: Q.service.en,
    questionVi: Q.service.vi,
    explanationEn: "Use を, not から: 1000円をお預かりします. 「〜から」is a common バイト敬語 error.",
    explanationVi: "Dùng を, không dùng から: 1000円をお預かりします. 「〜から」là lỗi バイト敬語 phổ biến.",
  },
  {
    id: "svc-yoroshikatta",
    type: "service",
    level: "N3",
    promptJa: "注文を確認するとき、正しいのは？",
    options: ["ご注文は以上でよろしかったでしょうか。", "ご注文は以上でよろしいでしょうか。", "ご注文は以上でいいですか。", "以上でOKでしょうか。"],
    correctIndex: 1,
    questionEn: Q.service.en,
    questionVi: Q.service.vi,
    explanationEn: "Confirm in the present: よろしいでしょうか. Past tense よろしかった is incorrect バイト敬語.",
    explanationVi: "Xác nhận ở hiện tại: よろしいでしょうか. Thì quá khứ よろしかった là バイト敬語 sai.",
  },
  {
    id: "svc-nohou",
    type: "service",
    level: "N3",
    promptJa: "飲み物を出すとき、正しいのは？",
    options: ["コーヒーのほうお持ちしました。", "コーヒーをお持ちしました。", "コーヒーになります。", "コーヒーの方です。"],
    correctIndex: 1,
    questionEn: Q.service.en,
    questionVi: Q.service.vi,
    explanationEn: "「〜のほう」and 「〜になります」are typical バイト敬語. Say コーヒーをお持ちしました.",
    explanationVi: "「〜のほう」và 「〜になります」là バイト敬語 điển hình. Nói コーヒーをお持ちしました.",
  },
  {
    id: "svc-amount",
    type: "service",
    level: "N2",
    promptJa: "会計金額を伝えるとき、正しいのは？",
    options: ["1万円になります。", "1万円でございます。", "1万円のほうになります。", "1万円からです。"],
    correctIndex: 1,
    questionEn: Q.service.en,
    questionVi: Q.service.vi,
    explanationEn: "For a fixed amount use でございます. 「〜になります」implies a change of state — misused here.",
    explanationVi: "Với số tiền cố định dùng でございます. 「〜になります」hàm ý biến đổi — dùng sai ở đây.",
  },
  {
    id: "svc-guide",
    type: "service",
    level: "N2",
    promptJa: "お客様を席へ案内するとき、正しいのは？",
    options: ["席のほうにご案内します。", "お席へご案内いたします。", "席まで行きますね。", "ご案内させていただいてもよろしいでしょうか。"],
    correctIndex: 1,
    questionEn: Q.service.en,
    questionVi: Q.service.vi,
    explanationEn: "お席へご案内いたします is clean and correct. 「のほう」is バイト敬語 and the させていただく version is over-polite.",
    explanationVi: "お席へご案内いたします gọn và đúng. 「のほう」là バイト敬語, còn bản させていただく thì lịch sự quá mức.",
  },
  {
    id: "svc-receipt",
    type: "service",
    level: "N3",
    promptJa: "レシートを渡すとき、正しいのは？",
    options: ["レシートのほうお返しします。", "レシートでございます。", "レシートになります。", "レシート大丈夫ですか。"],
    correctIndex: 1,
    questionEn: Q.service.en,
    questionVi: Q.service.vi,
    explanationEn: "Simply レシートでございます (or どうぞ). 「のほう」and 「になります」are バイト敬語 errors.",
    explanationVi: "Chỉ cần レシートでございます (hoặc どうぞ). 「のほう」và 「になります」là lỗi バイト敬語.",
  },
];

export function getDrillsByLevel(level?: AdaptiveLevel | "all"): Drill[] {
  if (!level || level === "all") return DRILLS;
  return DRILLS.filter((d) => d.level === level);
}

export function getDrillsByType(type?: DrillType | "all"): Drill[] {
  if (!type || type === "all") return DRILLS;
  return DRILLS.filter((d) => d.type === type);
}

export function filterDrills(level?: AdaptiveLevel | "all", type?: DrillType | "all"): Drill[] {
  return DRILLS.filter((d) => {
    if (level && level !== "all" && d.level !== level) return false;
    if (type && type !== "all" && d.type !== type) return false;
    return true;
  });
}
