import type { Scenario, ScenarioCategory, Difficulty } from "./types";

export const CATEGORY_LABELS: Record<ScenarioCategory, string> = {
  "daily-life": "Daily Life",
  workplace: "Workplace",
  "study-abroad": "Study Abroad",
  "job-interviews": "Job Interviews",
  "customer-service": "Customer Service",
  "business-japanese": "Business Japanese",
};

export const DIFFICULTY_LABELS: Record<Difficulty, string> = {
  beginner: "Beginner (N5–N4)",
  intermediate: "Intermediate (N3)",
  advanced: "Advanced (N2–N1)",
};

export const SCENARIOS: Scenario[] = [
  {
    id: "restaurant",
    title: "Restaurant Order",
    titleJa: "レストランで注文",
    category: "daily-life",
    difficulty: "beginner",
    description: "Practice ordering food at a Japanese restaurant.",
    aiRole: "Restaurant server",
    openingMessage: "いらっしゃいませ。ご注文はお決まりですか。",
    openingTranslation: "Welcome. Have you decided what you would like to order?",
    suggestedResponses: ["ラーメンを一つお願いします。", "メニューを見せてください。"],
  },
  {
    id: "convenience-store",
    title: "Convenience Store",
    titleJa: "コンビニ",
    category: "daily-life",
    difficulty: "beginner",
    description: "Buy items and handle simple requests at a konbini.",
    aiRole: "Store clerk",
    openingMessage: "いらっしゃいませ。お弁当は温めますか。",
    openingTranslation: "Welcome. Would you like your bento heated?",
    suggestedResponses: ["はい、温めてください。", "いいえ、大丈夫です。"],
  },
  {
    id: "directions",
    title: "Asking Directions",
    titleJa: "道を尋ねる",
    category: "daily-life",
    difficulty: "beginner",
    description: "Ask for and understand directions in the city.",
    aiRole: "Passerby",
    openingMessage: "すみません、何かお困りですか。",
    openingTranslation: "Excuse me, is something troubling you?",
    suggestedResponses: ["駅はどこですか。", "この地図で教えてください。"],
  },
  {
    id: "self-intro",
    title: "Self Introduction",
    titleJa: "自己紹介",
    category: "daily-life",
    difficulty: "beginner",
    description: "Introduce yourself in a casual social setting.",
    aiRole: "New acquaintance",
    openingMessage: "はじめまして。お名前は何ですか。",
    openingTranslation: "Nice to meet you. What is your name?",
    suggestedResponses: ["はじめまして。私は田中です。よろしくお願いします。"],
  },
  {
    id: "hospital",
    title: "Hospital Visit",
    titleJa: "病院",
    category: "daily-life",
    difficulty: "intermediate",
    description: "Describe symptoms and communicate at a clinic.",
    aiRole: "Receptionist",
    openingMessage: "お待ちください。本日はどのようなご用件でしょうか。",
    openingTranslation: "Please wait. What brings you in today?",
    suggestedResponses: ["頭が痛いので診察をお願いしたいです。"],
  },
  {
    id: "apartment",
    title: "Apartment Rental",
    titleJa: "アパート探し",
    category: "daily-life",
    difficulty: "intermediate",
    description: "Inquire about renting an apartment in Japan.",
    aiRole: "Real estate agent",
    openingMessage: "いらっしゃいませ。ご希望の条件を教えていただけますか。",
    openingTranslation: "Welcome. Could you tell me your preferred conditions?",
    suggestedResponses: ["駅から徒歩10分以内で、家賃は8万円以下を希望しています。"],
  },
  {
    id: "request-leave",
    title: "Requesting Time Off",
    titleJa: "休暇申請",
    category: "workplace",
    difficulty: "intermediate",
    description: "Request leave from your manager politely.",
    aiRole: "Manager",
    openingMessage: "お疲れ様です。何かありましたか。",
    openingTranslation: "Good work today. Is there something you need?",
    suggestedResponses: ["来週の金曜日、午後から休暇をいただきたいのですが。"],
  },
  {
    id: "workplace-meeting",
    title: "Team Meeting",
    titleJa: "チームミーティング",
    category: "workplace",
    difficulty: "intermediate",
    description: "Participate in a workplace team discussion.",
    aiRole: "Team lead",
    openingMessage: "それでは、今週の進捗を共有しましょう。",
    openingTranslation: "Let's share this week's progress.",
    suggestedResponses: ["私の担当分は予定通り進んでいます。"],
  },
  {
    id: "phone-call",
    title: "Phone Conversation",
    titleJa: "電話対応",
    category: "workplace",
    difficulty: "intermediate",
    description: "Handle a professional phone call at work.",
    aiRole: "Client",
    openingMessage: "お世話になっております。資料の件でお電話しました。",
    openingTranslation: "Thank you for your continued support. I'm calling about the documents.",
    suggestedResponses: ["お世話になっております。担当の佐藤が参りますので、少々お待ちください。"],
  },
  {
    id: "school-admin",
    title: "School Administration",
    titleJa: "学校事務",
    category: "study-abroad",
    difficulty: "intermediate",
    description: "Speak with school staff about enrollment or schedules.",
    aiRole: "School administrator",
    openingMessage: "いらっしゃいませ。どのようなご用件でしょうか。",
    openingTranslation: "Welcome. How may I help you?",
    suggestedResponses: ["来学期の履修登録について相談したいです。"],
  },
  {
    id: "classroom",
    title: "Classroom Discussion",
    titleJa: "授業での発言",
    category: "study-abroad",
    difficulty: "intermediate",
    description: "Participate in a classroom Q&A session.",
    aiRole: "Professor",
    openingMessage: "この問題について、意見のある人はいますか。",
    openingTranslation: "Does anyone have an opinion on this question?",
    suggestedResponses: ["私は環境問題が最も重要だと思います。"],
  },
  {
    id: "job-interview",
    title: "Job Interview",
    titleJa: "就職面接",
    category: "job-interviews",
    difficulty: "advanced",
    description: "Answer common interview questions in formal Japanese.",
    aiRole: "Interviewer",
    openingMessage: "本日はお時間をいただきありがとうございます。まず自己紹介をお願いします。",
    openingTranslation: "Thank you for your time today. Please start with a self-introduction.",
    suggestedResponses: [
      "本日は貴重なお時間をいただき、誠にありがとうございます。私は〇〇と申します。",
    ],
  },
  {
    id: "business-meeting",
    title: "Business Meeting",
    titleJa: "商談",
    category: "job-interviews",
    difficulty: "advanced",
    description: "Negotiate and present ideas in a business setting.",
    aiRole: "Business client",
    openingMessage: "本日の提案内容について、詳しくお聞かせください。",
    openingTranslation: "Please tell us more about today's proposal.",
    suggestedResponses: ["まず、市場調査の結果からご説明させていただきます。"],
  },
  {
    id: "customer-complaint",
    title: "Handling Complaints",
    titleJa: "クレーム対応",
    category: "customer-service",
    difficulty: "advanced",
    description: "Resolve a customer complaint professionally.",
    aiRole: "Upset customer",
    openingMessage: "先日購入した商品に不具合がありました。対応をお願いします。",
    openingTranslation: "The product I purchased recently has a defect. Please address this.",
    suggestedResponses: [
      "大変ご不便をおかけして申し訳ございません。すぐに確認いたします。",
    ],
  },
  {
    id: "supermarket",
    title: "Supermarket Shopping",
    titleJa: "スーパーで買い物",
    category: "daily-life",
    difficulty: "beginner",
    description: "Ask for help and make purchases at a supermarket.",
    aiRole: "Store staff",
    openingMessage: "いらっしゃいませ。何かお探しですか。",
    openingTranslation: "Welcome. Are you looking for something?",
    suggestedResponses: ["すみません、牛乳はどこにありますか。", "このりんごを一キロお願いします。"],
  },
  {
    id: "bank",
    title: "Bank Visit",
    titleJa: "銀行",
    category: "daily-life",
    difficulty: "intermediate",
    description: "Open an account or handle banking tasks in Japanese.",
    aiRole: "Bank teller",
    openingMessage: "いらっしゃいませ。本日はどのようなご用件でしょうか。",
    openingTranslation: "Welcome. How may I help you today?",
    suggestedResponses: ["口座を開設したいのですが、何が必要ですか。"],
  },
  {
    id: "post-office",
    title: "Post Office",
    titleJa: "郵便局",
    category: "daily-life",
    difficulty: "beginner",
    description: "Send a package or mail at the post office.",
    aiRole: "Postal clerk",
    openingMessage: "いらっしゃいませ。どのようなご用件ですか。",
    openingTranslation: "Welcome. What can I do for you?",
    suggestedResponses: ["この荷物をアメリカに送りたいです。", "切手を五枚ください。"],
  },
  {
    id: "train-station",
    title: "Public Transportation",
    titleJa: "電車・バス",
    category: "daily-life",
    difficulty: "beginner",
    description: "Buy tickets and ask about trains or buses.",
    aiRole: "Station staff",
    openingMessage: "すみません、どちらまで行かれますか。",
    openingTranslation: "Excuse me, where are you headed?",
    suggestedResponses: ["渋谷までの切符を買いたいです。", "この電車は新宿に停まりますか。"],
  },
  {
    id: "daily-report",
    title: "Daily Reporting",
    titleJa: "日報",
    category: "workplace",
    difficulty: "intermediate",
    description: "Give a daily work report to your manager.",
    aiRole: "Manager",
    openingMessage: "おはようございます。今日の予定を教えてください。",
    openingTranslation: "Good morning. Please tell me today's plan.",
    suggestedResponses: ["本日は資料の作成とクライアントへのメール返信を予定しています。"],
  },
  {
    id: "ask-question",
    title: "Asking Questions at Work",
    titleJa: "職場で質問",
    category: "workplace",
    difficulty: "intermediate",
    description: "Ask a senior colleague for help at work.",
    aiRole: "Senior colleague",
    openingMessage: "何か分からないことがあれば、聞いてください。",
    openingTranslation: "If anything is unclear, please ask.",
    suggestedResponses: ["この書類の書き方を教えていただけますか。"],
  },
  {
    id: "dormitory",
    title: "Dormitory Life",
    titleJa: "寮生活",
    category: "study-abroad",
    difficulty: "intermediate",
    description: "Talk with dorm staff about room issues or rules.",
    aiRole: "Dormitory manager",
    openingMessage: "どうしましたか。何か困ったことはありますか。",
    openingTranslation: "What's the matter? Is something troubling you?",
    suggestedResponses: ["部屋のエアコンが動かないので、修理をお願いしたいです。"],
  },
  {
    id: "club-activities",
    title: "Club Activities",
    titleJa: "サークル活動",
    category: "study-abroad",
    difficulty: "beginner",
    description: "Join a school club and talk with members.",
    aiRole: "Club senior member",
    openingMessage: "初めまして。サークルに興味があるんですね。",
    openingTranslation: "Nice to meet you. You're interested in our club?",
    suggestedResponses: ["はい、テニスが好きなので入りたいです。練習は何時ですか。"],
  },
  {
    id: "meeting-classmates",
    title: "Meeting Classmates",
    titleJa: "クラスメートと話す",
    category: "study-abroad",
    difficulty: "beginner",
    description: "Make friends and chat with classmates.",
    aiRole: "Classmate",
    openingMessage: "ねえ、昼ごはん一緒に食べない。",
    openingTranslation: "Hey, want to have lunch together?",
    suggestedResponses: ["いいね。どこに行く。", "ごめん、今日は用事があるんだ。"],
  },
  {
    id: "guide-customer",
    title: "Guiding Customers",
    titleJa: "お客様の案内",
    category: "customer-service",
    difficulty: "intermediate",
    description: "Help and guide customers in a store or facility.",
    aiRole: "Customer",
    openingMessage: "すみません、トイレはどこですか。",
    openingTranslation: "Excuse me, where is the restroom?",
    suggestedResponses: ["あちらの角を右に曲がってください。二階にございます。"],
  },
  {
    id: "interview-strengths",
    title: "Interview: Strengths",
    titleJa: "面接：長所と短所",
    category: "job-interviews",
    difficulty: "advanced",
    description: "Discuss your strengths and weaknesses in an interview.",
    aiRole: "Interviewer",
    openingMessage: "あなたの長所と短所を教えてください。",
    openingTranslation: "Please tell us about your strengths and weaknesses.",
    suggestedResponses: [
      "私の長所は責任感が強いことです。短所は完璧を求めすぎることで、改善に努めています。",
    ],
  },
  {
    id: "business-email",
    title: "Business Email",
    titleJa: "ビジネスメール",
    category: "business-japanese",
    difficulty: "intermediate",
    description: "Write and discuss professional emails in Japanese.",
    aiRole: "Email recipient",
    openingMessage: "先日のメール、拝見しました。詳細を確認させてください。",
    openingTranslation: "I read your email the other day. Let me confirm the details.",
    suggestedResponses: ["お忙しいところ恐れ入ります。資料を添付いたしましたのでご確認ください。"],
  },
  {
    id: "client-presentation",
    title: "Client Presentation",
    titleJa: "顧客へのプレゼン",
    category: "business-japanese",
    difficulty: "advanced",
    description: "Present proposals to a business client formally.",
    aiRole: "Executive client",
    openingMessage: "それでは、本日の提案の概要からお聞かせください。",
    openingTranslation: "Please start with an overview of today's proposal.",
    suggestedResponses: ["承知いたしました。まず課題認識からご説明させていただきます。"],
  },
  {
    id: "keigo-practice",
    title: "Keigo Practice",
    titleJa: "敬語練習",
    category: "business-japanese",
    difficulty: "advanced",
    description: "Practice respectful and humble language with a senior executive.",
    aiRole: "Executive client",
    openingMessage: "お忙しい中、お時間をいただきありがとうございます。",
    openingTranslation: "Thank you for your time despite your busy schedule.",
    suggestedResponses: ["こちらこそ、貴重なお時間をいただき、誠にありがとうございます。"],
  },
  {
    id: "office-etiquette",
    title: "Office Etiquette",
    titleJa: "職場マナー",
    category: "business-japanese",
    difficulty: "intermediate",
    description: "Navigate office customs, greetings, and polite exchanges.",
    aiRole: "HR manager",
    openingMessage: "新しいプロジェクトメンバーですね。よろしくお願いします。",
    openingTranslation: "You're the new project member. Pleased to work with you.",
    suggestedResponses: ["はじめまして。〇〇と申します。精一杯頑張りますので、よろしくお願いいたします。"],
  },
  {
    id: "salary-negotiation",
    title: "Salary Negotiation",
    titleJa: "給与交渉",
    category: "business-japanese",
    difficulty: "advanced",
    description: "Discuss compensation professionally with HR.",
    aiRole: "HR manager",
    openingMessage: "給与についてのご相談ですね。現状のお考えをお聞かせください。",
    openingTranslation: "This is about salary. Please share your current thinking.",
    suggestedResponses: ["昨年度の成果を踏まえ、昇給についてご相談させていただきたいです。"],
  },
  {
    id: "project-meeting",
    title: "Project Kickoff",
    titleJa: "プロジェクトキックオフ",
    category: "business-japanese",
    difficulty: "intermediate",
    description: "Lead or participate in a formal project kickoff meeting.",
    aiRole: "Meeting facilitator",
    openingMessage: "それでは、キックオフミーティングを始めさせていただきます。",
    openingTranslation: "Let us begin the kickoff meeting.",
    suggestedResponses: ["本日はよろしくお願いいたします。まずプロジェクトの目的から共有します。"],
  },
  {
    id: "pharmacy",
    title: "Pharmacy Visit",
    titleJa: "薬局",
    category: "daily-life",
    difficulty: "intermediate",
    description: "Describe symptoms and ask for medicine at a pharmacy.",
    aiRole: "Pharmacist",
    openingMessage: "いらっしゃいませ。どのような症状でしょうか。",
    openingTranslation: "Welcome. What symptoms are you experiencing?",
    suggestedResponses: ["のどが痛くて、熱も少しあります。市販の薬を教えてください。"],
  },
  {
    id: "hair-salon",
    title: "Hair Salon",
    titleJa: "美容院",
    category: "daily-life",
    difficulty: "beginner",
    description: "Book a haircut and explain your preferred style.",
    aiRole: "Hair stylist",
    openingMessage: "いらっしゃいませ。本日はどのようなスタイルにしますか。",
    openingTranslation: "Welcome. What style would you like today?",
    suggestedResponses: ["少し短く切ってください。前はそのままでお願いします。"],
  },
  {
    id: "hotel-checkin",
    title: "Hotel Check-in",
    titleJa: "ホテルチェックイン",
    category: "daily-life",
    difficulty: "intermediate",
    description: "Check in at a hotel and ask about amenities.",
    aiRole: "Hotel receptionist",
    openingMessage: "いらっしゃいませ。ご予約のお名前をお願いいたします。",
    openingTranslation: "Welcome. May I have the name on your reservation?",
    suggestedResponses: ["田中で予約しています。チェックインをお願いします。"],
  },
  {
    id: "izakaya",
    title: "Izakaya Order",
    titleJa: "居酒屋で注文",
    category: "daily-life",
    difficulty: "beginner",
    description: "Order food and drinks at a casual Japanese pub.",
    aiRole: "Izakaya staff",
    openingMessage: "いらっしゃいませ。お飲み物はいかがですか。",
    openingTranslation: "Welcome. What would you like to drink?",
    suggestedResponses: ["生ビールを二つと、枝豆をお願いします。"],
  },
  {
    id: "library",
    title: "Library Visit",
    titleJa: "図書館",
    category: "daily-life",
    difficulty: "beginner",
    description: "Borrow books and ask about library services.",
    aiRole: "Librarian",
    openingMessage: "いらっしゃいませ。何かお探しですか。",
    openingTranslation: "Welcome. Are you looking for something?",
    suggestedResponses: ["日本語の勉強本はどこにありますか。", "この本を借りたいです。"],
  },
  {
    id: "client-visit",
    title: "Client Site Visit",
    titleJa: "顧客先訪問",
    category: "workplace",
    difficulty: "advanced",
    description: "Greet and present updates during a client office visit.",
    aiRole: "Client",
    openingMessage: "お待ちしておりました。本日の進捗をお聞かせください。",
    openingTranslation: "We've been expecting you. Please share today's progress.",
    suggestedResponses: ["お世話になっております。資料をご用意しましたので、ご説明させていただきます。"],
  },
  {
    id: "work-handover",
    title: "Work Handover",
    titleJa: "業務引き継ぎ",
    category: "workplace",
    difficulty: "intermediate",
    description: "Hand off tasks and explain status to a colleague.",
    aiRole: "Senior colleague",
    openingMessage: "引き継ぎの件、よろしくお願いします。現状を教えてもらえますか。",
    openingTranslation: "Please handle the handover. Can you tell me the current status?",
    suggestedResponses: ["はい。現在の進捗と残タスクをまとめた資料があります。"],
  },
  {
    id: "part-time-interview",
    title: "Part-time Job Interview",
    titleJa: "アルバイト面接",
    category: "study-abroad",
    difficulty: "intermediate",
    description: "Interview for a part-time job as an international student.",
    aiRole: "Store manager",
    openingMessage: "本日はよろしくお願いします。週に何日働けますか。",
    openingTranslation: "Thank you for coming today. How many days per week can you work?",
    suggestedResponses: ["週に三日、午後から働けます。土日も大丈夫です。"],
  },
  {
    id: "school-festival",
    title: "School Festival",
    titleJa: "文化祭",
    category: "study-abroad",
    difficulty: "beginner",
    description: "Welcome visitors and sell items at a school festival booth.",
    aiRole: "Festival visitor",
    openingMessage: "すみません、このお店は何を売っていますか。",
    openingTranslation: "Excuse me, what does this booth sell?",
    suggestedResponses: ["いらっしゃいませ。たこ焼きです。一つ三百円です。"],
  },
  {
    id: "career-goals",
    title: "Interview: Career Goals",
    titleJa: "面接：志望動機",
    category: "job-interviews",
    difficulty: "advanced",
    description: "Explain your motivation and career goals in an interview.",
    aiRole: "Interviewer",
    openingMessage: "志望動機を教えてください。なぜ当社を選んだのですか。",
    openingTranslation: "Please tell us your motivation. Why did you choose our company?",
    suggestedResponses: [
      "御社のグローバル展開に魅力を感じ、自分の語学力を活かして貢献したいと考えました。",
    ],
  },
  {
    id: "previous-experience",
    title: "Interview: Work Experience",
    titleJa: "面接：職歴",
    category: "job-interviews",
    difficulty: "advanced",
    description: "Describe your previous work experience and responsibilities.",
    aiRole: "Interviewer",
    openingMessage: "前職ではどのような業務を担当されていましたか。",
    openingTranslation: "What kind of work did you handle at your previous job?",
    suggestedResponses: [
      "前職では営業職として、新規顧客の開拓と既存顧客のフォローを担当していました。",
    ],
  },
  {
    id: "behavioral-question",
    title: "Interview: Behavioral",
    titleJa: "面接：行動面接",
    category: "job-interviews",
    difficulty: "advanced",
    description: "Answer behavioral questions about teamwork and problem-solving.",
    aiRole: "Interviewer",
    openingMessage: "チームで困難な課題に直面した経験を教えてください。",
    openingTranslation: "Please tell us about a time your team faced a difficult challenge.",
    suggestedResponses: [
      "納期が迫る中、メンバーと役割分担を見直し、無事にプロジェクトを完了しました。",
    ],
  },
  {
    id: "product-explanation",
    title: "Product Explanation",
    titleJa: "商品説明",
    category: "customer-service",
    difficulty: "intermediate",
    description: "Explain product features and answer customer questions.",
    aiRole: "Curious customer",
    openingMessage: "この商品について詳しく教えてください。保証はありますか。",
    openingTranslation: "Please explain this product in detail. Does it come with a warranty?",
    suggestedResponses: ["はい、一年間のメーカー保証が付いています。主な機能をご説明します。"],
  },
  {
    id: "refund-request",
    title: "Refund Request",
    titleJa: "返金対応",
    category: "customer-service",
    difficulty: "advanced",
    description: "Handle a customer requesting a refund professionally.",
    aiRole: "Upset customer",
    openingMessage: "この商品は期待と違いました。返金してほしいのですが。",
    openingTranslation: "This product wasn't what I expected. I'd like a refund.",
    suggestedResponses: ["大変申し訳ございません。レシートを確認のうえ、返金手続きをいたします。"],
  },
  {
    id: "business-dinner",
    title: "Business Dinner",
    titleJa: "会食",
    category: "business-japanese",
    difficulty: "advanced",
    description: "Navigate formal toasts and conversation at a business dinner.",
    aiRole: "Executive client",
    openingMessage: "本日はお忙しい中、ありがとうございます。まず乾杯といきましょう。",
    openingTranslation: "Thank you for your time today. Let's start with a toast.",
    suggestedResponses: ["こちらこそ、お時間をいただきありがとうございます。乾杯。"],
  },
];

export function getBusinessScenarios(): Scenario[] {
  return SCENARIOS.filter((s) => s.category === "business-japanese");
}

export function getScenarioById(id: string): Scenario | undefined {
  return SCENARIOS.find((s) => s.id === id);
}

export function filterScenarios(
  category?: ScenarioCategory | "all",
  difficulty?: Difficulty | "all"
): Scenario[] {
  return SCENARIOS.filter((s) => {
    if (category && category !== "all" && s.category !== category) return false;
    if (difficulty && difficulty !== "all" && s.difficulty !== difficulty) return false;
    return true;
  });
}
